---
title: "noteMD (flexdashboard)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
    
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(reactable)
library(tidyverse)
library(leaflet)
library(sp)
library(htmltools)
library(noteMD)
```

Take notes & download 
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

### Download report 

Adjust the number of bins in the histogram.

```{r sliderInput-bins}
shiny::sliderInput(
  inputId = "bins", label = "Number of bins:", min = 1, max = 30, 
  value = 15
)
```

Change the point size in the scatter-plot. 

```{r sliderInput-points}
shiny::sliderInput(
  inputId = "point_size", label = "Size of points:", min = 1, max = 3, 
  value = 1, step = 0.5
)
```

Choose the file type you'd like to download and click on the **Download** button. 

```{r downloadButton-describe_download}
downloadButton(
  outputId = "describe_download",
  label = "Download Report",
  class = "butt"
)
```

```{r downloadHandler}
downloadHandler(

  # **create file name** ----
  filename = function() {
    paste("Summary", Sys.Date(), switch(
      input$format, PDF = ".pdf", Word = ".docx"
    ), sep = "")
  },
  # **(PDF) create content** ----
  content = function(file) {
    if (input$format == "PDF") {

      # **(PDF) start of progressing indicator** ----
      withProgress(
        message = "Download in progress",
        detail = "This may take a while...",
        value = 0,
        {
          for (i in 1:15) {
            incProgress(1 / 15)
            Sys.sleep(0.01)
          }
          # **(PDF) end of progression** ----

          src <- normalizePath("summary_report.Rmd")
          # temporarily switch to the temp dir, in case you do not have write
          # permission to the current working directory
          owd <- setwd(tempdir())
          on.exit(setwd(owd))

          file.copy(src, "summary_report.Rmd", overwrite = TRUE)

          library(rmarkdown)
          out <- render("summary_report.Rmd", pdf_document())
          file.rename(out, file)
        }
      )
      # **end of pdf content** ----
    } else {
      # **(DOCX) create content** ----
      # **(DOCX) start of progressing indicator** ----
      withProgress(
        message = "Download in progress",
        detail = "This may take a while...",
        value = 0,
        {
          for (i in 1:15) {
            # incremental progress
            incProgress(1 / 15)
            # set the Sys.sleep time
            Sys.sleep(0.01)
          }
          # (DOCX) end of progression ----

          src <- normalizePath("summary_report_word.Rmd")
          # temporarily switch to the temp dir, in case you do not have write
          # permission to the current working directory
          owd <- setwd(tempdir())
          on.exit(setwd(owd))
          file.copy(src, "summary_report_word.Rmd", overwrite = TRUE)

          library(rmarkdown)
          out <- render("summary_report_word.Rmd", word_document())
          file.rename(out, file)
        }
      )
    }
  }
)
```
      
```{r radioButtons-format}
radioButtons(
  inputId = "format",
  label = "Document format",
  choices = c("PDF", "Word"),
  inline = TRUE
)
```




Column 
-----------------------------------------------------------------------

```{r renderPlot-bins}
# renderPlot for plot histogram ----
renderPlot({
  carat_df <- dplyr::select(diamonds, carat)
  carat_df %>%
    ggplot(aes(x = carat)) +
    geom_histogram(bins = input$bins)
})
```


```{r helpText-tags-textarea-id-markdowninput_plot_1}
# helpText for note 1 ----
helpText("Note: make some comments about plot 1...")

# textarea id for note 1 ----
# use markdowninput prefix!
tags$textarea(
  "Please use **markdown** syntax!",
  id    = "markdowninput_plot_1",
  rows  = 3,
  style = "width:100%;"
)
```


```{r helpText-htmlOutput-outputId-htmlmarkdown_plot_1}
# helpText for Preview note 1 ----
helpText("Preview:")
# htmlOutput ----
# htmlmarkdown prefix!
htmlOutput(outputId = "htmlmarkdown_plot_1")
```

```{r output-htmlmarkdown-reactive-note_in_html-input-markdowninputplot}
# defines this as a reactive using the `input` value from `textarea` 
# (with `markdown_` prefix)and the `outputId` from htmlOutput (with 
# `htmlmarkdown_` prefix)
output$htmlmarkdown_plot_1 <- reactive({
  noteMD::note_in_html(input$markdowninput_plot_1)
})
```


Column 
-----------------------------------------------------------------------


```{r renderPlot-points}
# renderPlot bins ----
renderPlot({
  dplyr::select(ggplot2::diamonds, carat, price, cut) %>%  
   ggplot2::ggplot(aes(x = carat, y = price, color = cut)) + 
     ggplot2::geom_point(size = input$point_size)
})
```


```{r helpText-tags-textarea-markdowninput_plot_2}
# helpTex = Note... ----
helpText("Note: make some comments about plot 2...")
# textarea id (use markdowninput prefix!) 
tags$textarea(
  "Please use **markdown** syntax!",
  id    = "markdowninput_plot_2",
  rows  = 3,
  style = "width:100%;"
)
```


```{r helpText-htmlOutput-outputId-htmlmarkdown_plot_2}
# helpText = Preview 
helpText("Preview:")
# htmlOutput = use htmlmarkdown prefix!
shiny::htmlOutput(outputId = "htmlmarkdown_plot_2")
```

```{r output-htmlmarkdown_plot_2-note_in_html-input-markdowninput_plot_2}
# defines this as a reactive using the `input` value from `textarea` 
# (with `markdown_` prefix)and the `outputId` from htmlOutput (with 
# `htmlmarkdown_` prefix)
output$htmlmarkdown_plot_2 <- reactive({
  noteMD::note_in_html(input$markdowninput_plot_2)
})
```


